restylers_version: dev
restylers:
  - brittany:
      include:
        - "**/*.hs"
        - "!src/Blammo/Logging/Test.hs" # CPP
        - "!src/Data/Aeson/Compat.hs" # CPP
        - "!src/System/Log/FastLogger/Compat.hs" # CPP
  - "*"
