name: Blammo-wai
version: 0.0.0.0
maintainer: Freckle Education
category: Logging, Web
github: freckle/blammo
synopsis: Using Blammo with WAI
description: Please see README.md

extra-doc-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missing-exported-signatures # re-enables missing-signatures
  - -Wno-missing-import-lists
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-safe
  - -Wno-unsafe

when:
  - condition: "impl(ghc >= 9.8)"
    ghc-options:
      - -Wno-missing-role-annotations
  - condition: "impl(ghc >= 9.2)"
    ghc-options:
      - -Wno-missing-kind-signatures
  - condition: "impl(ghc >= 8.10)"
    ghc-options:
      - -Wno-missing-safe-haskell-mode
      - -Wno-prepositive-qualified-module

dependencies:
  - base < 5

default-extensions:
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - TypeApplications

library:
  source-dirs: src
  dependencies:
    - aeson
    - Blammo
    - bytestring
    - case-insensitive
    - clock
    - http-types
    - monad-logger-aeson
    - text
    - unliftio-core
    - wai

tests:
  readme:
    main: README.lhs
    ghc-options: -pgmL markdown-unlit
    dependencies:
      - Blammo
      - Blammo-wai
      - aeson
      - lens
      - markdown-unlit
      - text
      - wai
      - warp
      - yesod-core
